-- Create schema

CREATE TABLE BOOKS (
  BOOK_ID INT PRIMARY KEY NOT NULL,
  BOOK_NAME varchar(150),
  LEVEL INT NOT NULL UNIQUE
);

CREATE TABLE LESSONS (
  LESSON_ID PRIMARY KEY NOT NULL,
  BOOK_ID INT NOT NULL,
  FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

CREATE TABLE WORDS (
  WORD_ID INT PRIMARY KEY NOT NULL,
  LESSON_ID INT NOT NULL,
  KANJI varchar(150),
  KANA varchar(150),
  ROMANJI varchar(150),
  FOREIGN KEY(LESSON_ID) REFERENCES LESSONS(LESSON_ID)
);

CREATE TABLE TRANSLATIONS (
  WORD_ID INT PRIMARY KEY NOT NULL,
  TRANSLATION_EN varchar(150),
  FOREIGN KEY(WORD_ID) REFERENCES WORDS(WORD_ID)
);
